spring:
  h2:
    console:
      enabled: false
      path: /test_db
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./test_db;AUTO_SERVER=true
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  config: classpath:log4j2.xml
server:
  port: 8090